import Link from "next/link";
import {PageHeader} from "@/components/page-header";
import {StatusPill} from "@/components/status-pill";
import {adminRequest} from "@/lib/admin-api";

export default async function SeoPage(){
  const data=await adminRequest<any>("/v1/admin/operations/seo-overview",0);
  if(!data) throw new Error("SEO data unavailable.");

  return <>
    <PageHeader eyebrow="SEO / DISCOVERY OS / LIVE" title="Search, AI & discoverability" description="SEO coverage is calculated from canonical product, collection, media, entity and authority records—not demonstration scores.">
      <Link className="secondary-button" href="/seo/redirects">Redirect registry</Link>
    </PageHeader>

    <section className="stats-grid">
      <article className="stat-card"><span>SEO COVERAGE</span><strong>{data.coverage}%</strong><small>{data.seoDocuments} docs for {data.products+data.collections} indexable resources</small></article>
      <article className="stat-card"><span>IMAGE ALT COVERAGE</span><strong>{data.mediaAltCoverage}%</strong><small>{data.mediaWithAlt}/{data.mediaTotal} product media records</small></article>
      <article className="stat-card"><span>ENTITY FACTS</span><strong>{data.verifiedFacts}/{data.entityFacts}</strong><small>Verified brand facts</small></article>
      <article className="stat-card"><span>OPEN SEO WORK</span><strong>{data.openWorkItems}</strong><small>{data.authorityMentions} authority mentions recorded</small></article>
    </section>

    <section className="dashboard-grid">
      <article className="panel seo-deep-card">
        <div className="panel-head"><div><span>TECHNICAL SEO</span><h2>Implemented controls</h2></div></div>
        <div className="seo-check-list">
          {Object.entries(data.technical||{}).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><b>{value?"Pass":"Review"}</b><em>Live code</em></div>)}
          <div><span>Cloudflare image delivery</span><b>Deferred</b><em>Existing source URLs active</em></div>
        </div>
      </article>
      <article className="panel seo-deep-card">
        <div className="panel-head"><div><span>AI / ENTITY</span><h2>Verified first-party facts</h2></div></div>
        <div className="entity-fact-list">
          {(data.facts||[]).map((fact:any)=><div key={fact.id}><span className={fact.verified?"verified":"unverified"}>{fact.verified?"verified":"review"}</span><b>{fact.field}</b><p>{fact.value}</p><small>{fact.source_type||"internal"}</small></div>)}
          {!(data.facts||[]).length&&<div><b>No entity facts recorded yet.</b><p>Add factual brand identity only when it can be supported.</p></div>}
        </div>
      </article>
    </section>

    <section className="dashboard-grid lower">
      <article className="panel">
        <div className="panel-head"><div><span>WORK QUEUE</span><h2>Real SEO work items</h2></div><span className="seo-pill-muted">WHITE-HAT ONLY</span></div>
        {(data.workItems||[]).map((task:any)=><div className="seo-priority-row" key={task.id}><span className={"seo-task-priority "+task.priority}>{task.priority}</span><div><b>{task.title}</b><p>{task.reason}</p></div><small>{task.pillar}</small><span className={"seo-task-status "+task.status}>{task.status.replaceAll("_"," ")}</span></div>)}
        {!(data.workItems||[]).length&&<div className="empty-panel"><div><h2>No queued SEO tasks</h2><p>Product and collection SEO remain editable from their canonical resources.</p></div></div>}
      </article>
      <article className="panel">
        <div className="panel-head"><div><span>AUTHORITY</span><h2>Recorded mentions</h2></div></div>
        <div className="authority-table">
          {(data.authority||[]).map((item:any)=><div className="authority-row" key={item.id}><b>{item.source}</b><span>{item.mention_type}</span><span>{item.status}</span><em className={"authority-quality "+item.quality}>{item.quality}</em><small>{item.discovered_at?new Date(item.discovered_at).toLocaleDateString("en-PK"):"—"}</small></div>)}
          {!(data.authority||[]).length&&<div className="empty-panel"><div><h2>No authority claims fabricated</h2><p>Mentions/backlinks appear only when a real source is recorded.</p></div></div>}
        </div>
      </article>
    </section>

    <article className="panel policy-card allowed" style={{marginTop:14}}>
      <span>POLICY</span><h2>White-hat by default</h2><p>No fake reviews, fake community identities, fake authority citations, keyword stuffing or location spam are generated by this system.</p>
    </article>
  </>;
}
