import {PageHeader} from "@/components/page-header";
import {StatusPill} from "@/components/status-pill";
import {adminRequest} from "@/lib/admin-api";
import {recordPaymentAction,refundPaymentAction} from "@/app/enterprise-actions";

export default async function PaymentsPage(){
 const [data,orders]=await Promise.all([adminRequest<any>("/v1/admin/payments",0),adminRequest<any>("/v1/admin/orders",0)]);
 return <><PageHeader eyebrow="FINANCE / LEDGER" title="Payments" description="Provider-neutral payment transaction ledger for partial payments, captures, failures and refunds."/>
 <section className="enterprise-grid two"><article className="panel enterprise-card"><h3>Record payment</h3><form action={recordPaymentAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Order</span><select name="orderId" required>{(orders?.items||[]).map((o:any)=><option key={o.id} value={o.id}>{o.order_number} · {o.customer_name||"Guest"} · Rs. {Number(o.total).toLocaleString("en-PK")}</option>)}</select></label><label className="field"><span>Amount</span><input name="amount" type="number" min=".01" step=".01" required/></label><label className="field"><span>Provider</span><input name="provider" defaultValue="manual"/></label><label className="field"><span>Status</span><select name="status"><option value="succeeded">Succeeded</option><option value="pending">Pending</option><option value="failed">Failed</option></select></label><label className="field"><span>Reference</span><input name="externalId"/></label><label className="field"><span>Idempotency key</span><input name="idempotencyKey"/></label><button className="primary-button" type="submit">Record payment</button></form></article>
 <article className="panel enterprise-card"><h3>Record refund</h3><form action={refundPaymentAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Order</span><select name="orderId" required>{(orders?.items||[]).map((o:any)=><option key={o.id} value={o.id}>{o.order_number} · Rs. {Number(o.total).toLocaleString("en-PK")}</option>)}</select></label><label className="field"><span>Amount</span><input name="amount" type="number" min=".01" step=".01" required/></label><label className="field"><span>Provider</span><input name="provider" defaultValue="manual"/></label><label className="field"><span>Idempotency key</span><input name="idempotencyKey" required placeholder="refund-order-reason-001"/></label><button className="primary-button" type="submit">Record refund</button></form></article></section>
 <div className="panel table-wrap" style={{marginTop:14}}><table className="data-table"><thead><tr><th>TIME</th><th>TYPE</th><th>PROVIDER</th><th>STATUS</th><th>ORDER</th><th className="right">AMOUNT</th></tr></thead><tbody>{(data?.items||[]).map((t:any)=><tr key={t.id}><td>{new Date(t.created_at).toLocaleString("en-PK")}</td><td>{t.transaction_type}</td><td>{t.provider}</td><td><StatusPill tone={t.status==="succeeded"?"success":t.status==="failed"?"danger":"warning"}>{t.status}</StatusPill></td><td><small>{t.order_id||"Draft"}</small></td><td className="right">Rs. {Number(t.amount).toLocaleString("en-PK")}</td></tr>)}</tbody></table></div></>;
}
