"use client";

import {useState} from "react";
import {channelListings,salesChannels,seoDocument} from "@/lib/mock-data";

export function ProductSeoChannelManager({productId}:{productId:string}){
  const [title,setTitle]=useState(seoDocument.title);
  const [description,setDescription]=useState(seoDocument.metaDescription);
  const listings=channelListings.filter(x=>x.productId===productId);
  return <section className="seo-channel-grid">
    <article className="panel seo-editor"><div className="panel-head"><div><span>SEARCH PRESENTATION</span><h2>Product SEO</h2></div><strong className="seo-score">{seoDocument.score}</strong></div><div className="seo-fields"><label className="seo-field wide"><span>SEO title</span><input value={title} onChange={e=>setTitle(e.target.value)}/><small className="seo-counter">{title.length} chars</small></label><label className="seo-field wide"><span>Meta description</span><textarea value={description} onChange={e=>setDescription(e.target.value)}/><small className="seo-counter">{description.length} chars</small></label><label className="seo-field"><span>Canonical path</span><input defaultValue={seoDocument.canonicalPath}/></label><label className="seo-field"><span>Schema type</span><select defaultValue={seoDocument.schemaType}><option>Product</option><option>WebPage</option></select></label></div><div className="seo-preview"><span>SEARCH PREVIEW</span><h4>{title}</h4><a>{"jewelry-store-lime.vercel.app"+seoDocument.canonicalPath}</a><p>{description}</p><div className="schema-chips"><span>Product</span><span>Offer</span><span>BreadcrumbList</span></div></div></article>
    <article className="panel seo-editor"><div className="panel-head"><div><span>MULTICHANNEL OVERLAYS</span><h2>Publish once, tailor per channel</h2></div></div><div className="channel-hub-grid">{salesChannels.slice(0,5).map(channel=>{const listing=listings.find(x=>x.channelId===channel.id);return <div className="channel-publish-card" key={channel.id}><div className="channel-publish-head"><div><span>{channel.type.toUpperCase()}</span><b>{channel.name}</b></div><em className={"publish-state "+(listing?.syncStatus==="synced"?"synced":"draft")}>{listing?.status??"not published"}</em></div><p>{listing?.titleOverride??"Uses canonical product title"}</p><div className="channel-publish-meta"><small>{listing?.categoryExternalId?"Category "+listing.categoryExternalId:"Canonical category"}</small><small>{listing?.lastSyncAt??"Never"}</small></div></div>})}</div><div className="channel-override-editor"><p>Channel records can override presentation, category mapping, price or media order without creating a second canonical product or variant.</p></div></article>
  </section>
}