alter table stores enable row level security;
alter table products enable row level security;
alter table product_options enable row level security;
alter table product_option_values enable row level security;
alter table product_variants enable row level security;
alter table variant_option_values enable row level security;
alter table product_media_sets enable row level security;
alter table product_media enable row level security;
alter table media_renditions enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table conversations enable row level security;
alter table jobs enable row level security;
alter table seo_documents enable row level security;
alter table url_redirects enable row level security;
alter table sales_channels enable row level security;
alter table channel_publications enable row level security;
alter table external_resource_mappings enable row level security;
alter table seo_work_items enable row level security;
alter table entity_facts enable row level security;
alter table authority_mentions enable row level security;

revoke all on table stores from anon, authenticated;
revoke all on table products from anon, authenticated;
revoke all on table product_options from anon, authenticated;
revoke all on table product_option_values from anon, authenticated;
revoke all on table product_variants from anon, authenticated;
revoke all on table variant_option_values from anon, authenticated;
revoke all on table product_media_sets from anon, authenticated;
revoke all on table product_media from anon, authenticated;
revoke all on table media_renditions from anon, authenticated;
revoke all on table customers from anon, authenticated;
revoke all on table orders from anon, authenticated;
revoke all on table conversations from anon, authenticated;
revoke all on table jobs from anon, authenticated;
revoke all on table seo_documents from anon, authenticated;
revoke all on table url_redirects from anon, authenticated;
revoke all on table sales_channels from anon, authenticated;
revoke all on table channel_publications from anon, authenticated;
revoke all on table external_resource_mappings from anon, authenticated;
revoke all on table seo_work_items from anon, authenticated;
revoke all on table entity_facts from anon, authenticated;
revoke all on table authority_mentions from anon, authenticated;

create index if not exists product_options_product_id_idx on product_options(product_id);
create index if not exists product_option_values_option_id_idx on product_option_values(option_id);
create index if not exists product_variants_media_set_id_idx on product_variants(media_set_id);
create index if not exists variant_option_values_option_value_id_idx on variant_option_values(option_value_id);
create index if not exists product_media_sets_product_id_idx on product_media_sets(product_id);
create index if not exists product_media_media_set_id_idx on product_media(media_set_id);
create index if not exists orders_customer_id_idx on orders(customer_id);
create index if not exists conversations_store_id_idx on conversations(store_id);
create index if not exists conversations_customer_id_idx on conversations(customer_id);
create index if not exists jobs_store_id_idx on jobs(store_id);
create index if not exists channel_publications_product_id_idx on channel_publications(product_id);
create index if not exists channel_publications_media_set_id_idx on channel_publications(media_set_id);
create index if not exists external_resource_mappings_store_id_idx on external_resource_mappings(store_id);
create index if not exists seo_work_items_store_id_idx on seo_work_items(store_id);
create index if not exists entity_facts_store_id_idx on entity_facts(store_id);
create index if not exists authority_mentions_store_id_idx on authority_mentions(store_id);
