import {PageHeader} from "@/components/page-header";
import {adminRequest} from "@/lib/admin-api";
import {adjustLocationInventoryAction,createLocationAction} from "@/app/enterprise-actions";

export default async function InventoryPage(){
  const [locations,levels,catalog]=await Promise.all([adminRequest<any>("/v1/admin/locations",0),adminRequest<any>("/v1/admin/inventory-levels",0),adminRequest<any>("/v1/admin/order-catalog",0)]);
  const loc=locations?.items||[],items=levels?.items||[],variants=catalog?.items||[];
  const total=items.reduce((sum:number,row:any)=>sum+Number(row.available||0),0),incoming=items.reduce((sum:number,row:any)=>sum+Number(row.incoming||0),0);
  return <>
    <PageHeader eyebrow="INVENTORY / LOCATIONS" title="Inventory" description="Canonical stock by fulfillment location with audited adjustments and aggregate storefront availability."/>
    <section className="stats-grid"><article className="stat-card"><span>LOCATIONS</span><strong>{loc.length}</strong></article><article className="stat-card"><span>AVAILABLE UNITS</span><strong>{total}</strong></article><article className="stat-card"><span>INCOMING</span><strong>{incoming}</strong></article><article className="stat-card"><span>SKU LEVELS</span><strong>{items.length}</strong></article></section>
    <section className="dashboard-grid"><article className="panel enterprise-card"><h3>Add location</h3><form action={createLocationAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Name</span><input name="name" required/></label><label className="field"><span>Code</span><input name="code" required/></label><label className="field"><span>Address</span><input name="line1"/></label><label className="field"><span>City</span><input name="city"/></label><label className="field"><span>Region</span><input name="region"/></label><label className="field"><span>Country</span><input name="country" defaultValue="Pakistan"/></label><label className="field"><span>Fulfillment</span><input name="isFulfillment" type="checkbox" defaultChecked/></label><label className="field"><span>Make default</span><input name="makeDefault" type="checkbox"/></label><button className="primary-button" type="submit">Add location</button></form></article>
    <article className="panel enterprise-card"><h3>Adjust stock</h3><form action={adjustLocationInventoryAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Location</span><select name="locationId" required>{loc.map((l:any)=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><label className="field"><span>Variant</span><select name="variantId" required>{variants.map((v:any)=><option value={v.variant_id} key={v.variant_id}>{v.title} · {v.sku}</option>)}</select></label><label className="field"><span>Delta</span><input name="delta" type="number" placeholder="+5 / -2" required/></label><label className="field"><span>Reason</span><input name="reason" required/></label><button className="primary-button" type="submit">Adjust inventory</button></form></article></section>
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>LOCATION</th><th>PRODUCT</th><th>SKU</th><th>AVAILABLE</th><th>RESERVED</th><th>INCOMING</th><th className="right">COST</th></tr></thead><tbody>{items.map((i:any)=><tr key={i.id}><td><b>{i.location_name}</b><small>{i.location_code}</small></td><td>{i.product_title}</td><td>{i.sku}</td><td>{i.available}</td><td>{i.reserved}</td><td>{i.incoming}</td><td className="right">Rs. {Number(i.cost_amount||0).toLocaleString("en-PK")}</td></tr>)}{!items.length&&<tr><td colSpan={7}>No inventory levels.</td></tr>}</tbody></table></div>
  </>;
}
