import {PageHeader} from "@/components/page-header";
import {adminRequest} from "@/lib/admin-api";
import {createShippingRateAction,createShippingZoneAction,createTaxRuleAction,updateTaxModeAction} from "@/app/enterprise-actions";

export default async function ShippingPage(){
  const [shipping,taxes]=await Promise.all([adminRequest<any>("/v1/admin/shipping",0),adminRequest<any>("/v1/admin/taxes",0)]);
  const zones=shipping?.zones||[],rates=shipping?.rates||[],taxRules=taxes?.items||[];
  return <>
    <PageHeader eyebrow="FULFILLMENT / PRICING" title="Shipping & tax" description="Region/city shipping zones, value/weight thresholds, carrier metadata and jurisdiction-aware tax rules."/>
    <section className="enterprise-grid">
      <article className="panel enterprise-card"><h3>Shipping zone</h3><form action={createShippingZoneAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Name</span><input name="name" required/></label><label className="field"><span>Priority</span><input name="priority" type="number" defaultValue="0"/></label><label className="field"><span>Countries</span><input name="countries" defaultValue="Pakistan"/></label><label className="field"><span>Regions</span><input name="regions" placeholder="Punjab,Sindh"/></label><label className="field" style={{gridColumn:"1 / -1"}}><span>Cities</span><input name="cities" placeholder="Lahore,Karachi,Islamabad"/></label><button className="primary-button" type="submit">Add zone</button></form></article>
      <article className="panel enterprise-card"><h3>Shipping rate</h3><form action={createShippingRateAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Zone</span><select name="zoneId" required>{zones.map((z:any)=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="field"><span>Name</span><input name="name" required placeholder="Standard"/></label><label className="field"><span>Type</span><select name="rateType"><option value="flat">Flat</option><option value="free">Free</option><option value="weight">Weight based</option><option value="order_value">Order value</option></select></label><label className="field"><span>Amount</span><input name="amount" type="number" min="0" defaultValue="0"/></label><label className="field"><span>Min order</span><input name="minOrderValue" type="number"/></label><label className="field"><span>Max order</span><input name="maxOrderValue" type="number"/></label><label className="field"><span>Min weight g</span><input name="minWeightGrams" type="number"/></label><label className="field"><span>Max weight g</span><input name="maxWeightGrams" type="number"/></label><label className="field"><span>Carrier</span><input name="carrier"/></label><label className="field"><span>Service code</span><input name="serviceCode"/></label><button className="primary-button" type="submit">Add rate</button></form></article>
      <article className="panel enterprise-card"><h3>Tax rule</h3><form action={createTaxRuleAction} className="field-grid" style={{marginTop:16}}><label className="field"><span>Name</span><input name="name" required/></label><label className="field"><span>Rate %</span><input name="rate" type="number" min="0" max="100" step=".001" required/></label><label className="field"><span>Country</span><input name="country" defaultValue="Pakistan"/></label><label className="field"><span>Region</span><input name="region"/></label><label className="field"><span>City</span><input name="city"/></label><label className="field"><span>Product types</span><input name="productTypes" placeholder="Rings,Necklaces"/></label><button className="primary-button" type="submit">Add tax rule</button></form><form action={updateTaxModeAction} style={{marginTop:18}}><label className="field"><span>Prices include tax</span><input type="checkbox" name="pricesIncludeTax" defaultChecked={Boolean(taxes?.pricesIncludeTax)}/></label><button className="secondary-button" type="submit">Save tax mode</button></form></article>
    </section>
    <section className="dashboard-grid" style={{marginTop:14}}><article className="panel"><div className="panel-head"><div><span>SHIPPING</span><h2>Configured rates</h2></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>ZONE</th><th>RATE</th><th>TYPE</th><th>CARRIER</th><th className="right">AMOUNT</th></tr></thead><tbody>{rates.map((r:any)=>{const z=zones.find((x:any)=>x.id===r.zone_id);return <tr key={r.id}><td>{z?.name||"—"}</td><td>{r.name}</td><td>{r.rate_type}</td><td>{r.carrier||"—"}</td><td className="right">Rs. {Number(r.amount).toLocaleString("en-PK")}</td></tr>})}</tbody></table></div></article><article className="panel"><div className="panel-head"><div><span>TAX</span><h2>Jurisdiction rules</h2></div></div><div className="activity-list">{taxRules.map((t:any)=><div className="activity-item" key={t.id}><span>•</span><div><b>{t.name} · {(Number(t.rate)*100).toFixed(2)}%</b><p>{[t.city,t.region,t.country].filter(Boolean).join(", ")||"Global"} · {(t.product_types||[]).join(", ")||"All taxable products"}</p></div></div>)}</div></article></section>
  </>;
}
